### ISSUE TITLE
Code snippets in upload section should be identical to those shown below

### ISSUE THREAD

**Issue by salieflewis** [web3-storage/www#63]
https://web3.storage/docs/how-to/upload/

vs.

https://github.com/web3-storage/w3up/tree/main/packages/w3up-client#bringing-your-own-agent-and-delegation

--

Just generally it is pretty confusing to see the same idea being expressed but with a slightly different implementation. Even if that just means the lack of identical comments or import statements.

**Comment by travis** [comment]
Thanks! I made a few updates. Some of the comments remain different, but that is intentional due to the context in which the snippets are presented.
